-- 美食清單（跟著景點）
CREATE TABLE IF NOT EXISTS food_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  trip_id INTEGER NOT NULL,
  spot_id INTEGER,
  spot_name TEXT NOT NULL DEFAULT '',
  day INTEGER NOT NULL DEFAULT 1,
  assignee TEXT NOT NULL,
  item TEXT NOT NULL,
  is_eaten INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY(trip_id) REFERENCES trips(id) ON DELETE CASCADE
);
